import { z } from "zod";

export const profissionalSchema = z.object({
  id: z.string().optional(),
  nome_completo: z.string().min(1, "Nome é obrigatório"),
  nome_social: z.string().nullish().default(""),
  cpf: z.string().nullish().default(""),
  matricula: z.string().nullish().default(""),
  email: z.string().email("E-mail inválido").nullish().or(z.literal("")).default(""),
  telefone: z.string().nullish().default(""),
  data_nascimento: z.string().nullish().default(""),
  sexo: z.string().nullish().default(""),
  data_admissao: z.string().nullish().default(""),
  carga_horaria_semanal: z.string().nullish().default(""),
  status: z.string().default("ativo"),
  observacoes: z.string().nullish().default(""),
  secretaria_id: z.string().min(1, "Secretaria é obrigatória"),
  unidade_id: z.string().nullish().default(""),
  setor_id: z.string().nullish().default(""),
  cargo_id: z.string().nullish().default(""),
  funcao_id: z.string().nullish().default(""),
  vinculo_id: z.string().nullish().default(""),
  cep: z.string().nullish().default(""),
  logradouro: z.string().nullish().default(""),
  numero: z.string().nullish().default(""),
  bairro: z.string().nullish().default(""),
  cidade: z.string().nullish().default(""),
  uf: z.string().nullish().default(""),
  banco: z.string().nullish().default(""),
  agencia: z.string().nullish().default(""),
  conta_corrente: z.string().nullish().default(""),
  proj: z.string().nullish().default(""),
  h_p: z.string().nullish().default(""),
  c_h: z.string().nullish().default(""),
  jorn: z.string().nullish().default(""),
  conselho_classe: z.string().nullish().default(""),
  conselho_numero: z.string().nullish().default(""),
  conselho_uf: z.string().nullish().default(""),
  conselho_validade: z.string().nullish().default(""),
  gestor_imediato_id: z.string().nullish().default(""),
  situacao_funcional: z.string().nullish().default(""),
  situacao_data_inicio: z.string().nullish().default(""),
  situacao_data_fim: z.string().nullish().default(""),
  foto_url: z.string().nullish().default(""),
});

export type ProfissionalFormValues = z.infer<typeof profissionalSchema>;
