/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmtpTestRouteImport } from './routes/smtp-test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarIdRouteImport } from './routes/validar.$id'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTiposUnidadeRouteImport } from './routes/_authenticated/tipos-unidade'
import { Route as AuthenticatedSetoresRouteImport } from './routes/_authenticated/setores'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedSaudeRouteImport } from './routes/_authenticated/saude'
import { Route as AuthenticatedSalaSituacaoRouteImport } from './routes/_authenticated/sala-situacao'
import { Route as AuthenticatedRelatoriosStatusRouteImport } from './routes/_authenticated/relatorios-status'
import { Route as AuthenticatedRelatoriosProfissionalRouteImport } from './routes/_authenticated/relatorios-profissional'
import { Route as AuthenticatedRelatoriosPisoRouteImport } from './routes/_authenticated/relatorios-piso'
import { Route as AuthenticatedRelatoriosGerenciaisRouteImport } from './routes/_authenticated/relatorios-gerenciais'
import { Route as AuthenticatedRelatoriosExecutivoRouteImport } from './routes/_authenticated/relatorios-executivo'
import { Route as AuthenticatedRelatoriosConsolidadoRouteImport } from './routes/_authenticated/relatorios-consolidado'
import { Route as AuthenticatedRelatoriosCadastroRouteImport } from './routes/_authenticated/relatorios-cadastro'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRelatorioInteligenteRouteImport } from './routes/_authenticated/relatorio-inteligente'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedLayoutsImportacaoRouteImport } from './routes/_authenticated/layouts-importacao'
import { Route as AuthenticatedGestaoRhRouteImport } from './routes/_authenticated/gestao-rh'
import { Route as AuthenticatedGestaoProfissionaisRouteImport } from './routes/_authenticated/gestao-profissionais'
import { Route as AuthenticatedFrequenciasRouteImport } from './routes/_authenticated/frequencias'
import { Route as AuthenticatedFeriadosRouteImport } from './routes/_authenticated/feriados'
import { Route as AuthenticatedDocumentosEmitidosRouteImport } from './routes/_authenticated/documentos-emitidos'
import { Route as AuthenticatedControleForcaTrabalhoRouteImport } from './routes/_authenticated/controle-forca-trabalho'
import { Route as AuthenticatedCompetenciasRouteImport } from './routes/_authenticated/competencias'
import { Route as AuthenticatedCargosFuncoesRouteImport } from './routes/_authenticated/cargos-funcoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedAssinarPdfRouteImport } from './routes/_authenticated/assinar-pdf'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedAnaliticoRouteImport } from './routes/_authenticated/analitico'
import { Route as AuthenticatedUnidadesIndexRouteImport } from './routes/_authenticated/unidades.index'
import { Route as AuthenticatedRelatoriosGerenciaisIndexRouteImport } from './routes/_authenticated/relatorios-gerenciais.index'
import { Route as AuthenticatedPisoEnfermagemIndexRouteImport } from './routes/_authenticated/piso-enfermagem.index'
import { Route as AuthenticatedGestaoPessoasIndexRouteImport } from './routes/_authenticated/gestao-pessoas.index'
import { Route as AuthenticatedConfiguracaoIndexRouteImport } from './routes/_authenticated/configuracao.index'
import { Route as AuthenticatedUsuariosIdRouteImport } from './routes/_authenticated/usuarios.$id'
import { Route as AuthenticatedUnidadesIdRouteImport } from './routes/_authenticated/unidades.$id'
import { Route as AuthenticatedSetoresIdRouteImport } from './routes/_authenticated/setores.$id'
import { Route as AuthenticatedRelatoriosGerenciaisUnidadesRouteImport } from './routes/_authenticated/relatorios-gerenciais.unidades'
import { Route as AuthenticatedRelatoriosGerenciaisSetoresRouteImport } from './routes/_authenticated/relatorios-gerenciais.setores'
import { Route as AuthenticatedRelatoriosGerenciaisSalariosRouteImport } from './routes/_authenticated/relatorios-gerenciais.salarios'
import { Route as AuthenticatedRelatoriosGerenciaisProfissionaisRouteImport } from './routes/_authenticated/relatorios-gerenciais.profissionais'
import { Route as AuthenticatedRelatoriosGerenciaisPisoRouteImport } from './routes/_authenticated/relatorios-gerenciais.piso'
import { Route as AuthenticatedRelatoriosGerenciaisFuncoesRouteImport } from './routes/_authenticated/relatorios-gerenciais.funcoes'
import { Route as AuthenticatedRelatoriosGerenciaisEstruturaRouteImport } from './routes/_authenticated/relatorios-gerenciais.estrutura'
import { Route as AuthenticatedRelatoriosGerenciaisCargosRouteImport } from './routes/_authenticated/relatorios-gerenciais.cargos'
import { Route as AuthenticatedRelatoriosGerenciaisAuditoriaRouteImport } from './routes/_authenticated/relatorios-gerenciais.auditoria'
import { Route as AuthenticatedProfissionaisIdRouteImport } from './routes/_authenticated/profissionais.$id'
import { Route as AuthenticatedPisoEnfermagemImportarEfetivosRouteImport } from './routes/_authenticated/piso-enfermagem.importar-efetivos'
import { Route as AuthenticatedPisoEnfermagemImportarContratadosRouteImport } from './routes/_authenticated/piso-enfermagem.importar-contratados'
import { Route as AuthenticatedPisoEnfermagemImportarRouteImport } from './routes/_authenticated/piso-enfermagem.importar'
import { Route as AuthenticatedPisoEnfermagemExtracaoRouteImport } from './routes/_authenticated/piso-enfermagem.extracao'
import { Route as AuthenticatedMeuPerfilAssinaturaRouteImport } from './routes/_authenticated/meu-perfil.assinatura'
import { Route as AuthenticatedGestaoPessoasSituacaoFuncionalRouteImport } from './routes/_authenticated/gestao-pessoas.situacao-funcional'
import { Route as AuthenticatedGestaoPessoasLotacaoRouteImport } from './routes/_authenticated/gestao-pessoas.lotacao'
import { Route as AuthenticatedGestaoPessoasDistribuicaoSetorRouteImport } from './routes/_authenticated/gestao-pessoas.distribuicao-setor'
import { Route as AuthenticatedFuncoesIdRouteImport } from './routes/_authenticated/funcoes.$id'
import { Route as AuthenticatedFrequenciasIdRouteImport } from './routes/_authenticated/frequencias_.$id'
import { Route as AuthenticatedFrequenciaEfetivosRouteImport } from './routes/_authenticated/frequencia.efetivos'
import { Route as AuthenticatedFrequenciaContratadosRouteImport } from './routes/_authenticated/frequencia.contratados'
import { Route as AuthenticatedConfiguracaoPerfisRouteImport } from './routes/_authenticated/configuracao.perfis'
import { Route as AuthenticatedCompetenciasIdRouteImport } from './routes/_authenticated/competencias.$id'
import { Route as AuthenticatedCargosIdRouteImport } from './routes/_authenticated/cargos.$id'
import { Route as AuthenticatedAdministracaoSistemasExternosRouteImport } from './routes/_authenticated/administracao/sistemas-externos'
import { Route as AuthenticatedAdministracaoMuralRouteImport } from './routes/_authenticated/administracao/mural'
import { Route as ApiPublicHooksPurgarDocumentosRouteImport } from './routes/api/public/hooks/purgar-documentos'
import { Route as ApiPublicHooksEventosWorkerRouteImport } from './routes/api/public/hooks/eventos-worker'
import { Route as ApiPublicHooksDeadlineCheckRouteImport } from './routes/api/public/hooks/deadline-check'
import { Route as ApiPublicDocumentoPdfIdRouteImport } from './routes/api/public/documento-pdf.$id'
import { Route as AuthenticatedConfiguracaoPerfisIdRouteImport } from './routes/_authenticated/configuracao.perfis.$id'

const SmtpTestRoute = SmtpTestRouteImport.update({
  id: '/smtp-test',
  path: '/smtp-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarIdRoute = ValidarIdRouteImport.update({
  id: '/validar/$id',
  path: '/validar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTiposUnidadeRoute =
  AuthenticatedTiposUnidadeRouteImport.update({
    id: '/tipos-unidade',
    path: '/tipos-unidade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetoresRoute = AuthenticatedSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSaudeRoute = AuthenticatedSaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalaSituacaoRoute =
  AuthenticatedSalaSituacaoRouteImport.update({
    id: '/sala-situacao',
    path: '/sala-situacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosStatusRoute =
  AuthenticatedRelatoriosStatusRouteImport.update({
    id: '/relatorios-status',
    path: '/relatorios-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosProfissionalRoute =
  AuthenticatedRelatoriosProfissionalRouteImport.update({
    id: '/relatorios-profissional',
    path: '/relatorios-profissional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosPisoRoute =
  AuthenticatedRelatoriosPisoRouteImport.update({
    id: '/relatorios-piso',
    path: '/relatorios-piso',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisRoute =
  AuthenticatedRelatoriosGerenciaisRouteImport.update({
    id: '/relatorios-gerenciais',
    path: '/relatorios-gerenciais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosExecutivoRoute =
  AuthenticatedRelatoriosExecutivoRouteImport.update({
    id: '/relatorios-executivo',
    path: '/relatorios-executivo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosConsolidadoRoute =
  AuthenticatedRelatoriosConsolidadoRouteImport.update({
    id: '/relatorios-consolidado',
    path: '/relatorios-consolidado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosCadastroRoute =
  AuthenticatedRelatoriosCadastroRouteImport.update({
    id: '/relatorios-cadastro',
    path: '/relatorios-cadastro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatorioInteligenteRoute =
  AuthenticatedRelatorioInteligenteRouteImport.update({
    id: '/relatorio-inteligente',
    path: '/relatorio-inteligente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLayoutsImportacaoRoute =
  AuthenticatedLayoutsImportacaoRouteImport.update({
    id: '/layouts-importacao',
    path: '/layouts-importacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoRhRoute = AuthenticatedGestaoRhRouteImport.update({
  id: '/gestao-rh',
  path: '/gestao-rh',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGestaoProfissionaisRoute =
  AuthenticatedGestaoProfissionaisRouteImport.update({
    id: '/gestao-profissionais',
    path: '/gestao-profissionais',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrequenciasRoute =
  AuthenticatedFrequenciasRouteImport.update({
    id: '/frequencias',
    path: '/frequencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeriadosRoute = AuthenticatedFeriadosRouteImport.update({
  id: '/feriados',
  path: '/feriados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosEmitidosRoute =
  AuthenticatedDocumentosEmitidosRouteImport.update({
    id: '/documentos-emitidos',
    path: '/documentos-emitidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControleForcaTrabalhoRoute =
  AuthenticatedControleForcaTrabalhoRouteImport.update({
    id: '/controle-forca-trabalho',
    path: '/controle-forca-trabalho',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompetenciasRoute =
  AuthenticatedCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCargosFuncoesRoute =
  AuthenticatedCargosFuncoesRouteImport.update({
    id: '/cargos-funcoes',
    path: '/cargos-funcoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssinarPdfRoute = AuthenticatedAssinarPdfRouteImport.update({
  id: '/assinar-pdf',
  path: '/assinar-pdf',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnaliticoRoute = AuthenticatedAnaliticoRouteImport.update({
  id: '/analitico',
  path: '/analitico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnidadesIndexRoute =
  AuthenticatedUnidadesIndexRouteImport.update({
    id: '/unidades/',
    path: '/unidades/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisIndexRoute =
  AuthenticatedRelatoriosGerenciaisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedPisoEnfermagemIndexRoute =
  AuthenticatedPisoEnfermagemIndexRouteImport.update({
    id: '/piso-enfermagem/',
    path: '/piso-enfermagem/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoPessoasIndexRoute =
  AuthenticatedGestaoPessoasIndexRouteImport.update({
    id: '/gestao-pessoas/',
    path: '/gestao-pessoas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracaoIndexRoute =
  AuthenticatedConfiguracaoIndexRouteImport.update({
    id: '/configuracao/',
    path: '/configuracao/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsuariosIdRoute = AuthenticatedUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsuariosRoute,
} as any)
const AuthenticatedUnidadesIdRoute = AuthenticatedUnidadesIdRouteImport.update({
  id: '/unidades/$id',
  path: '/unidades/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetoresIdRoute = AuthenticatedSetoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSetoresRoute,
} as any)
const AuthenticatedRelatoriosGerenciaisUnidadesRoute =
  AuthenticatedRelatoriosGerenciaisUnidadesRouteImport.update({
    id: '/unidades',
    path: '/unidades',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisSetoresRoute =
  AuthenticatedRelatoriosGerenciaisSetoresRouteImport.update({
    id: '/setores',
    path: '/setores',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisSalariosRoute =
  AuthenticatedRelatoriosGerenciaisSalariosRouteImport.update({
    id: '/salarios',
    path: '/salarios',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisProfissionaisRoute =
  AuthenticatedRelatoriosGerenciaisProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisPisoRoute =
  AuthenticatedRelatoriosGerenciaisPisoRouteImport.update({
    id: '/piso',
    path: '/piso',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisFuncoesRoute =
  AuthenticatedRelatoriosGerenciaisFuncoesRouteImport.update({
    id: '/funcoes',
    path: '/funcoes',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisEstruturaRoute =
  AuthenticatedRelatoriosGerenciaisEstruturaRouteImport.update({
    id: '/estrutura',
    path: '/estrutura',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisCargosRoute =
  AuthenticatedRelatoriosGerenciaisCargosRouteImport.update({
    id: '/cargos',
    path: '/cargos',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedRelatoriosGerenciaisAuditoriaRoute =
  AuthenticatedRelatoriosGerenciaisAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedRelatoriosGerenciaisRoute,
  } as any)
const AuthenticatedProfissionaisIdRoute =
  AuthenticatedProfissionaisIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProfissionaisRoute,
  } as any)
const AuthenticatedPisoEnfermagemImportarEfetivosRoute =
  AuthenticatedPisoEnfermagemImportarEfetivosRouteImport.update({
    id: '/piso-enfermagem/importar-efetivos',
    path: '/piso-enfermagem/importar-efetivos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPisoEnfermagemImportarContratadosRoute =
  AuthenticatedPisoEnfermagemImportarContratadosRouteImport.update({
    id: '/piso-enfermagem/importar-contratados',
    path: '/piso-enfermagem/importar-contratados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPisoEnfermagemImportarRoute =
  AuthenticatedPisoEnfermagemImportarRouteImport.update({
    id: '/piso-enfermagem/importar',
    path: '/piso-enfermagem/importar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPisoEnfermagemExtracaoRoute =
  AuthenticatedPisoEnfermagemExtracaoRouteImport.update({
    id: '/piso-enfermagem/extracao',
    path: '/piso-enfermagem/extracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeuPerfilAssinaturaRoute =
  AuthenticatedMeuPerfilAssinaturaRouteImport.update({
    id: '/meu-perfil/assinatura',
    path: '/meu-perfil/assinatura',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoPessoasSituacaoFuncionalRoute =
  AuthenticatedGestaoPessoasSituacaoFuncionalRouteImport.update({
    id: '/gestao-pessoas/situacao-funcional',
    path: '/gestao-pessoas/situacao-funcional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoPessoasLotacaoRoute =
  AuthenticatedGestaoPessoasLotacaoRouteImport.update({
    id: '/gestao-pessoas/lotacao',
    path: '/gestao-pessoas/lotacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGestaoPessoasDistribuicaoSetorRoute =
  AuthenticatedGestaoPessoasDistribuicaoSetorRouteImport.update({
    id: '/gestao-pessoas/distribuicao-setor',
    path: '/gestao-pessoas/distribuicao-setor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFuncoesIdRoute = AuthenticatedFuncoesIdRouteImport.update({
  id: '/funcoes/$id',
  path: '/funcoes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFrequenciasIdRoute =
  AuthenticatedFrequenciasIdRouteImport.update({
    id: '/frequencias_/$id',
    path: '/frequencias/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrequenciaEfetivosRoute =
  AuthenticatedFrequenciaEfetivosRouteImport.update({
    id: '/frequencia/efetivos',
    path: '/frequencia/efetivos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFrequenciaContratadosRoute =
  AuthenticatedFrequenciaContratadosRouteImport.update({
    id: '/frequencia/contratados',
    path: '/frequencia/contratados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracaoPerfisRoute =
  AuthenticatedConfiguracaoPerfisRouteImport.update({
    id: '/configuracao/perfis',
    path: '/configuracao/perfis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompetenciasIdRoute =
  AuthenticatedCompetenciasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCompetenciasRoute,
  } as any)
const AuthenticatedCargosIdRoute = AuthenticatedCargosIdRouteImport.update({
  id: '/cargos/$id',
  path: '/cargos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministracaoSistemasExternosRoute =
  AuthenticatedAdministracaoSistemasExternosRouteImport.update({
    id: '/administracao/sistemas-externos',
    path: '/administracao/sistemas-externos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracaoMuralRoute =
  AuthenticatedAdministracaoMuralRouteImport.update({
    id: '/administracao/mural',
    path: '/administracao/mural',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksPurgarDocumentosRoute =
  ApiPublicHooksPurgarDocumentosRouteImport.update({
    id: '/api/public/hooks/purgar-documentos',
    path: '/api/public/hooks/purgar-documentos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEventosWorkerRoute =
  ApiPublicHooksEventosWorkerRouteImport.update({
    id: '/api/public/hooks/eventos-worker',
    path: '/api/public/hooks/eventos-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeadlineCheckRoute =
  ApiPublicHooksDeadlineCheckRouteImport.update({
    id: '/api/public/hooks/deadline-check',
    path: '/api/public/hooks/deadline-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDocumentoPdfIdRoute = ApiPublicDocumentoPdfIdRouteImport.update({
  id: '/api/public/documento-pdf/$id',
  path: '/api/public/documento-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracaoPerfisIdRoute =
  AuthenticatedConfiguracaoPerfisIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConfiguracaoPerfisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smtp-test': typeof SmtpTestRoute
  '/analitico': typeof AuthenticatedAnaliticoRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/assinar-pdf': typeof AuthenticatedAssinarPdfRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cargos-funcoes': typeof AuthenticatedCargosFuncoesRoute
  '/competencias': typeof AuthenticatedCompetenciasRouteWithChildren
  '/controle-forca-trabalho': typeof AuthenticatedControleForcaTrabalhoRoute
  '/documentos-emitidos': typeof AuthenticatedDocumentosEmitidosRoute
  '/feriados': typeof AuthenticatedFeriadosRoute
  '/frequencias': typeof AuthenticatedFrequenciasRoute
  '/gestao-profissionais': typeof AuthenticatedGestaoProfissionaisRoute
  '/gestao-rh': typeof AuthenticatedGestaoRhRoute
  '/layouts-importacao': typeof AuthenticatedLayoutsImportacaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRouteWithChildren
  '/relatorio-inteligente': typeof AuthenticatedRelatorioInteligenteRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-cadastro': typeof AuthenticatedRelatoriosCadastroRoute
  '/relatorios-consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/relatorios-executivo': typeof AuthenticatedRelatoriosExecutivoRoute
  '/relatorios-gerenciais': typeof AuthenticatedRelatoriosGerenciaisRouteWithChildren
  '/relatorios-piso': typeof AuthenticatedRelatoriosPisoRoute
  '/relatorios-profissional': typeof AuthenticatedRelatoriosProfissionalRoute
  '/relatorios-status': typeof AuthenticatedRelatoriosStatusRoute
  '/sala-situacao': typeof AuthenticatedSalaSituacaoRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/setores': typeof AuthenticatedSetoresRouteWithChildren
  '/tipos-unidade': typeof AuthenticatedTiposUnidadeRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/validar/$id': typeof ValidarIdRoute
  '/administracao/mural': typeof AuthenticatedAdministracaoMuralRoute
  '/administracao/sistemas-externos': typeof AuthenticatedAdministracaoSistemasExternosRoute
  '/cargos/$id': typeof AuthenticatedCargosIdRoute
  '/competencias/$id': typeof AuthenticatedCompetenciasIdRoute
  '/configuracao/perfis': typeof AuthenticatedConfiguracaoPerfisRouteWithChildren
  '/frequencia/contratados': typeof AuthenticatedFrequenciaContratadosRoute
  '/frequencia/efetivos': typeof AuthenticatedFrequenciaEfetivosRoute
  '/frequencias/$id': typeof AuthenticatedFrequenciasIdRoute
  '/funcoes/$id': typeof AuthenticatedFuncoesIdRoute
  '/gestao-pessoas/distribuicao-setor': typeof AuthenticatedGestaoPessoasDistribuicaoSetorRoute
  '/gestao-pessoas/lotacao': typeof AuthenticatedGestaoPessoasLotacaoRoute
  '/gestao-pessoas/situacao-funcional': typeof AuthenticatedGestaoPessoasSituacaoFuncionalRoute
  '/meu-perfil/assinatura': typeof AuthenticatedMeuPerfilAssinaturaRoute
  '/piso-enfermagem/extracao': typeof AuthenticatedPisoEnfermagemExtracaoRoute
  '/piso-enfermagem/importar': typeof AuthenticatedPisoEnfermagemImportarRoute
  '/piso-enfermagem/importar-contratados': typeof AuthenticatedPisoEnfermagemImportarContratadosRoute
  '/piso-enfermagem/importar-efetivos': typeof AuthenticatedPisoEnfermagemImportarEfetivosRoute
  '/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/relatorios-gerenciais/auditoria': typeof AuthenticatedRelatoriosGerenciaisAuditoriaRoute
  '/relatorios-gerenciais/cargos': typeof AuthenticatedRelatoriosGerenciaisCargosRoute
  '/relatorios-gerenciais/estrutura': typeof AuthenticatedRelatoriosGerenciaisEstruturaRoute
  '/relatorios-gerenciais/funcoes': typeof AuthenticatedRelatoriosGerenciaisFuncoesRoute
  '/relatorios-gerenciais/piso': typeof AuthenticatedRelatoriosGerenciaisPisoRoute
  '/relatorios-gerenciais/profissionais': typeof AuthenticatedRelatoriosGerenciaisProfissionaisRoute
  '/relatorios-gerenciais/salarios': typeof AuthenticatedRelatoriosGerenciaisSalariosRoute
  '/relatorios-gerenciais/setores': typeof AuthenticatedRelatoriosGerenciaisSetoresRoute
  '/relatorios-gerenciais/unidades': typeof AuthenticatedRelatoriosGerenciaisUnidadesRoute
  '/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/configuracao/': typeof AuthenticatedConfiguracaoIndexRoute
  '/gestao-pessoas/': typeof AuthenticatedGestaoPessoasIndexRoute
  '/piso-enfermagem/': typeof AuthenticatedPisoEnfermagemIndexRoute
  '/relatorios-gerenciais/': typeof AuthenticatedRelatoriosGerenciaisIndexRoute
  '/unidades/': typeof AuthenticatedUnidadesIndexRoute
  '/configuracao/perfis/$id': typeof AuthenticatedConfiguracaoPerfisIdRoute
  '/api/public/documento-pdf/$id': typeof ApiPublicDocumentoPdfIdRoute
  '/api/public/hooks/deadline-check': typeof ApiPublicHooksDeadlineCheckRoute
  '/api/public/hooks/eventos-worker': typeof ApiPublicHooksEventosWorkerRoute
  '/api/public/hooks/purgar-documentos': typeof ApiPublicHooksPurgarDocumentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smtp-test': typeof SmtpTestRoute
  '/analitico': typeof AuthenticatedAnaliticoRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/assinar-pdf': typeof AuthenticatedAssinarPdfRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cargos-funcoes': typeof AuthenticatedCargosFuncoesRoute
  '/competencias': typeof AuthenticatedCompetenciasRouteWithChildren
  '/controle-forca-trabalho': typeof AuthenticatedControleForcaTrabalhoRoute
  '/documentos-emitidos': typeof AuthenticatedDocumentosEmitidosRoute
  '/feriados': typeof AuthenticatedFeriadosRoute
  '/frequencias': typeof AuthenticatedFrequenciasRoute
  '/gestao-profissionais': typeof AuthenticatedGestaoProfissionaisRoute
  '/gestao-rh': typeof AuthenticatedGestaoRhRoute
  '/layouts-importacao': typeof AuthenticatedLayoutsImportacaoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRouteWithChildren
  '/relatorio-inteligente': typeof AuthenticatedRelatorioInteligenteRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/relatorios-cadastro': typeof AuthenticatedRelatoriosCadastroRoute
  '/relatorios-consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/relatorios-executivo': typeof AuthenticatedRelatoriosExecutivoRoute
  '/relatorios-piso': typeof AuthenticatedRelatoriosPisoRoute
  '/relatorios-profissional': typeof AuthenticatedRelatoriosProfissionalRoute
  '/relatorios-status': typeof AuthenticatedRelatoriosStatusRoute
  '/sala-situacao': typeof AuthenticatedSalaSituacaoRoute
  '/saude': typeof AuthenticatedSaudeRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/setores': typeof AuthenticatedSetoresRouteWithChildren
  '/tipos-unidade': typeof AuthenticatedTiposUnidadeRoute
  '/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/validar/$id': typeof ValidarIdRoute
  '/administracao/mural': typeof AuthenticatedAdministracaoMuralRoute
  '/administracao/sistemas-externos': typeof AuthenticatedAdministracaoSistemasExternosRoute
  '/cargos/$id': typeof AuthenticatedCargosIdRoute
  '/competencias/$id': typeof AuthenticatedCompetenciasIdRoute
  '/configuracao/perfis': typeof AuthenticatedConfiguracaoPerfisRouteWithChildren
  '/frequencia/contratados': typeof AuthenticatedFrequenciaContratadosRoute
  '/frequencia/efetivos': typeof AuthenticatedFrequenciaEfetivosRoute
  '/frequencias/$id': typeof AuthenticatedFrequenciasIdRoute
  '/funcoes/$id': typeof AuthenticatedFuncoesIdRoute
  '/gestao-pessoas/distribuicao-setor': typeof AuthenticatedGestaoPessoasDistribuicaoSetorRoute
  '/gestao-pessoas/lotacao': typeof AuthenticatedGestaoPessoasLotacaoRoute
  '/gestao-pessoas/situacao-funcional': typeof AuthenticatedGestaoPessoasSituacaoFuncionalRoute
  '/meu-perfil/assinatura': typeof AuthenticatedMeuPerfilAssinaturaRoute
  '/piso-enfermagem/extracao': typeof AuthenticatedPisoEnfermagemExtracaoRoute
  '/piso-enfermagem/importar': typeof AuthenticatedPisoEnfermagemImportarRoute
  '/piso-enfermagem/importar-contratados': typeof AuthenticatedPisoEnfermagemImportarContratadosRoute
  '/piso-enfermagem/importar-efetivos': typeof AuthenticatedPisoEnfermagemImportarEfetivosRoute
  '/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/relatorios-gerenciais/auditoria': typeof AuthenticatedRelatoriosGerenciaisAuditoriaRoute
  '/relatorios-gerenciais/cargos': typeof AuthenticatedRelatoriosGerenciaisCargosRoute
  '/relatorios-gerenciais/estrutura': typeof AuthenticatedRelatoriosGerenciaisEstruturaRoute
  '/relatorios-gerenciais/funcoes': typeof AuthenticatedRelatoriosGerenciaisFuncoesRoute
  '/relatorios-gerenciais/piso': typeof AuthenticatedRelatoriosGerenciaisPisoRoute
  '/relatorios-gerenciais/profissionais': typeof AuthenticatedRelatoriosGerenciaisProfissionaisRoute
  '/relatorios-gerenciais/salarios': typeof AuthenticatedRelatoriosGerenciaisSalariosRoute
  '/relatorios-gerenciais/setores': typeof AuthenticatedRelatoriosGerenciaisSetoresRoute
  '/relatorios-gerenciais/unidades': typeof AuthenticatedRelatoriosGerenciaisUnidadesRoute
  '/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/configuracao': typeof AuthenticatedConfiguracaoIndexRoute
  '/gestao-pessoas': typeof AuthenticatedGestaoPessoasIndexRoute
  '/piso-enfermagem': typeof AuthenticatedPisoEnfermagemIndexRoute
  '/relatorios-gerenciais': typeof AuthenticatedRelatoriosGerenciaisIndexRoute
  '/unidades': typeof AuthenticatedUnidadesIndexRoute
  '/configuracao/perfis/$id': typeof AuthenticatedConfiguracaoPerfisIdRoute
  '/api/public/documento-pdf/$id': typeof ApiPublicDocumentoPdfIdRoute
  '/api/public/hooks/deadline-check': typeof ApiPublicHooksDeadlineCheckRoute
  '/api/public/hooks/eventos-worker': typeof ApiPublicHooksEventosWorkerRoute
  '/api/public/hooks/purgar-documentos': typeof ApiPublicHooksPurgarDocumentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/smtp-test': typeof SmtpTestRoute
  '/_authenticated/analitico': typeof AuthenticatedAnaliticoRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/assinar-pdf': typeof AuthenticatedAssinarPdfRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cargos-funcoes': typeof AuthenticatedCargosFuncoesRoute
  '/_authenticated/competencias': typeof AuthenticatedCompetenciasRouteWithChildren
  '/_authenticated/controle-forca-trabalho': typeof AuthenticatedControleForcaTrabalhoRoute
  '/_authenticated/documentos-emitidos': typeof AuthenticatedDocumentosEmitidosRoute
  '/_authenticated/feriados': typeof AuthenticatedFeriadosRoute
  '/_authenticated/frequencias': typeof AuthenticatedFrequenciasRoute
  '/_authenticated/gestao-profissionais': typeof AuthenticatedGestaoProfissionaisRoute
  '/_authenticated/gestao-rh': typeof AuthenticatedGestaoRhRoute
  '/_authenticated/layouts-importacao': typeof AuthenticatedLayoutsImportacaoRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRouteWithChildren
  '/_authenticated/relatorio-inteligente': typeof AuthenticatedRelatorioInteligenteRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/relatorios-cadastro': typeof AuthenticatedRelatoriosCadastroRoute
  '/_authenticated/relatorios-consolidado': typeof AuthenticatedRelatoriosConsolidadoRoute
  '/_authenticated/relatorios-executivo': typeof AuthenticatedRelatoriosExecutivoRoute
  '/_authenticated/relatorios-gerenciais': typeof AuthenticatedRelatoriosGerenciaisRouteWithChildren
  '/_authenticated/relatorios-piso': typeof AuthenticatedRelatoriosPisoRoute
  '/_authenticated/relatorios-profissional': typeof AuthenticatedRelatoriosProfissionalRoute
  '/_authenticated/relatorios-status': typeof AuthenticatedRelatoriosStatusRoute
  '/_authenticated/sala-situacao': typeof AuthenticatedSalaSituacaoRoute
  '/_authenticated/saude': typeof AuthenticatedSaudeRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/_authenticated/setores': typeof AuthenticatedSetoresRouteWithChildren
  '/_authenticated/tipos-unidade': typeof AuthenticatedTiposUnidadeRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRouteWithChildren
  '/validar/$id': typeof ValidarIdRoute
  '/_authenticated/administracao/mural': typeof AuthenticatedAdministracaoMuralRoute
  '/_authenticated/administracao/sistemas-externos': typeof AuthenticatedAdministracaoSistemasExternosRoute
  '/_authenticated/cargos/$id': typeof AuthenticatedCargosIdRoute
  '/_authenticated/competencias/$id': typeof AuthenticatedCompetenciasIdRoute
  '/_authenticated/configuracao/perfis': typeof AuthenticatedConfiguracaoPerfisRouteWithChildren
  '/_authenticated/frequencia/contratados': typeof AuthenticatedFrequenciaContratadosRoute
  '/_authenticated/frequencia/efetivos': typeof AuthenticatedFrequenciaEfetivosRoute
  '/_authenticated/frequencias_/$id': typeof AuthenticatedFrequenciasIdRoute
  '/_authenticated/funcoes/$id': typeof AuthenticatedFuncoesIdRoute
  '/_authenticated/gestao-pessoas/distribuicao-setor': typeof AuthenticatedGestaoPessoasDistribuicaoSetorRoute
  '/_authenticated/gestao-pessoas/lotacao': typeof AuthenticatedGestaoPessoasLotacaoRoute
  '/_authenticated/gestao-pessoas/situacao-funcional': typeof AuthenticatedGestaoPessoasSituacaoFuncionalRoute
  '/_authenticated/meu-perfil/assinatura': typeof AuthenticatedMeuPerfilAssinaturaRoute
  '/_authenticated/piso-enfermagem/extracao': typeof AuthenticatedPisoEnfermagemExtracaoRoute
  '/_authenticated/piso-enfermagem/importar': typeof AuthenticatedPisoEnfermagemImportarRoute
  '/_authenticated/piso-enfermagem/importar-contratados': typeof AuthenticatedPisoEnfermagemImportarContratadosRoute
  '/_authenticated/piso-enfermagem/importar-efetivos': typeof AuthenticatedPisoEnfermagemImportarEfetivosRoute
  '/_authenticated/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/_authenticated/relatorios-gerenciais/auditoria': typeof AuthenticatedRelatoriosGerenciaisAuditoriaRoute
  '/_authenticated/relatorios-gerenciais/cargos': typeof AuthenticatedRelatoriosGerenciaisCargosRoute
  '/_authenticated/relatorios-gerenciais/estrutura': typeof AuthenticatedRelatoriosGerenciaisEstruturaRoute
  '/_authenticated/relatorios-gerenciais/funcoes': typeof AuthenticatedRelatoriosGerenciaisFuncoesRoute
  '/_authenticated/relatorios-gerenciais/piso': typeof AuthenticatedRelatoriosGerenciaisPisoRoute
  '/_authenticated/relatorios-gerenciais/profissionais': typeof AuthenticatedRelatoriosGerenciaisProfissionaisRoute
  '/_authenticated/relatorios-gerenciais/salarios': typeof AuthenticatedRelatoriosGerenciaisSalariosRoute
  '/_authenticated/relatorios-gerenciais/setores': typeof AuthenticatedRelatoriosGerenciaisSetoresRoute
  '/_authenticated/relatorios-gerenciais/unidades': typeof AuthenticatedRelatoriosGerenciaisUnidadesRoute
  '/_authenticated/setores/$id': typeof AuthenticatedSetoresIdRoute
  '/_authenticated/unidades/$id': typeof AuthenticatedUnidadesIdRoute
  '/_authenticated/usuarios/$id': typeof AuthenticatedUsuariosIdRoute
  '/_authenticated/configuracao/': typeof AuthenticatedConfiguracaoIndexRoute
  '/_authenticated/gestao-pessoas/': typeof AuthenticatedGestaoPessoasIndexRoute
  '/_authenticated/piso-enfermagem/': typeof AuthenticatedPisoEnfermagemIndexRoute
  '/_authenticated/relatorios-gerenciais/': typeof AuthenticatedRelatoriosGerenciaisIndexRoute
  '/_authenticated/unidades/': typeof AuthenticatedUnidadesIndexRoute
  '/_authenticated/configuracao/perfis/$id': typeof AuthenticatedConfiguracaoPerfisIdRoute
  '/api/public/documento-pdf/$id': typeof ApiPublicDocumentoPdfIdRoute
  '/api/public/hooks/deadline-check': typeof ApiPublicHooksDeadlineCheckRoute
  '/api/public/hooks/eventos-worker': typeof ApiPublicHooksEventosWorkerRoute
  '/api/public/hooks/purgar-documentos': typeof ApiPublicHooksPurgarDocumentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/smtp-test'
    | '/analitico'
    | '/aprovacoes'
    | '/assinar-pdf'
    | '/assinaturas'
    | '/auditoria'
    | '/cargos-funcoes'
    | '/competencias'
    | '/controle-forca-trabalho'
    | '/documentos-emitidos'
    | '/feriados'
    | '/frequencias'
    | '/gestao-profissionais'
    | '/gestao-rh'
    | '/layouts-importacao'
    | '/notificacoes'
    | '/pendencias'
    | '/profissionais'
    | '/relatorio-inteligente'
    | '/relatorios'
    | '/relatorios-cadastro'
    | '/relatorios-consolidado'
    | '/relatorios-executivo'
    | '/relatorios-gerenciais'
    | '/relatorios-piso'
    | '/relatorios-profissional'
    | '/relatorios-status'
    | '/sala-situacao'
    | '/saude'
    | '/seguranca'
    | '/setores'
    | '/tipos-unidade'
    | '/usuarios'
    | '/validar/$id'
    | '/administracao/mural'
    | '/administracao/sistemas-externos'
    | '/cargos/$id'
    | '/competencias/$id'
    | '/configuracao/perfis'
    | '/frequencia/contratados'
    | '/frequencia/efetivos'
    | '/frequencias/$id'
    | '/funcoes/$id'
    | '/gestao-pessoas/distribuicao-setor'
    | '/gestao-pessoas/lotacao'
    | '/gestao-pessoas/situacao-funcional'
    | '/meu-perfil/assinatura'
    | '/piso-enfermagem/extracao'
    | '/piso-enfermagem/importar'
    | '/piso-enfermagem/importar-contratados'
    | '/piso-enfermagem/importar-efetivos'
    | '/profissionais/$id'
    | '/relatorios-gerenciais/auditoria'
    | '/relatorios-gerenciais/cargos'
    | '/relatorios-gerenciais/estrutura'
    | '/relatorios-gerenciais/funcoes'
    | '/relatorios-gerenciais/piso'
    | '/relatorios-gerenciais/profissionais'
    | '/relatorios-gerenciais/salarios'
    | '/relatorios-gerenciais/setores'
    | '/relatorios-gerenciais/unidades'
    | '/setores/$id'
    | '/unidades/$id'
    | '/usuarios/$id'
    | '/configuracao/'
    | '/gestao-pessoas/'
    | '/piso-enfermagem/'
    | '/relatorios-gerenciais/'
    | '/unidades/'
    | '/configuracao/perfis/$id'
    | '/api/public/documento-pdf/$id'
    | '/api/public/hooks/deadline-check'
    | '/api/public/hooks/eventos-worker'
    | '/api/public/hooks/purgar-documentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/smtp-test'
    | '/analitico'
    | '/aprovacoes'
    | '/assinar-pdf'
    | '/assinaturas'
    | '/auditoria'
    | '/cargos-funcoes'
    | '/competencias'
    | '/controle-forca-trabalho'
    | '/documentos-emitidos'
    | '/feriados'
    | '/frequencias'
    | '/gestao-profissionais'
    | '/gestao-rh'
    | '/layouts-importacao'
    | '/notificacoes'
    | '/pendencias'
    | '/profissionais'
    | '/relatorio-inteligente'
    | '/relatorios'
    | '/relatorios-cadastro'
    | '/relatorios-consolidado'
    | '/relatorios-executivo'
    | '/relatorios-piso'
    | '/relatorios-profissional'
    | '/relatorios-status'
    | '/sala-situacao'
    | '/saude'
    | '/seguranca'
    | '/setores'
    | '/tipos-unidade'
    | '/usuarios'
    | '/validar/$id'
    | '/administracao/mural'
    | '/administracao/sistemas-externos'
    | '/cargos/$id'
    | '/competencias/$id'
    | '/configuracao/perfis'
    | '/frequencia/contratados'
    | '/frequencia/efetivos'
    | '/frequencias/$id'
    | '/funcoes/$id'
    | '/gestao-pessoas/distribuicao-setor'
    | '/gestao-pessoas/lotacao'
    | '/gestao-pessoas/situacao-funcional'
    | '/meu-perfil/assinatura'
    | '/piso-enfermagem/extracao'
    | '/piso-enfermagem/importar'
    | '/piso-enfermagem/importar-contratados'
    | '/piso-enfermagem/importar-efetivos'
    | '/profissionais/$id'
    | '/relatorios-gerenciais/auditoria'
    | '/relatorios-gerenciais/cargos'
    | '/relatorios-gerenciais/estrutura'
    | '/relatorios-gerenciais/funcoes'
    | '/relatorios-gerenciais/piso'
    | '/relatorios-gerenciais/profissionais'
    | '/relatorios-gerenciais/salarios'
    | '/relatorios-gerenciais/setores'
    | '/relatorios-gerenciais/unidades'
    | '/setores/$id'
    | '/unidades/$id'
    | '/usuarios/$id'
    | '/configuracao'
    | '/gestao-pessoas'
    | '/piso-enfermagem'
    | '/relatorios-gerenciais'
    | '/unidades'
    | '/configuracao/perfis/$id'
    | '/api/public/documento-pdf/$id'
    | '/api/public/hooks/deadline-check'
    | '/api/public/hooks/eventos-worker'
    | '/api/public/hooks/purgar-documentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/reset-password'
    | '/smtp-test'
    | '/_authenticated/analitico'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/assinar-pdf'
    | '/_authenticated/assinaturas'
    | '/_authenticated/auditoria'
    | '/_authenticated/cargos-funcoes'
    | '/_authenticated/competencias'
    | '/_authenticated/controle-forca-trabalho'
    | '/_authenticated/documentos-emitidos'
    | '/_authenticated/feriados'
    | '/_authenticated/frequencias'
    | '/_authenticated/gestao-profissionais'
    | '/_authenticated/gestao-rh'
    | '/_authenticated/layouts-importacao'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pendencias'
    | '/_authenticated/profissionais'
    | '/_authenticated/relatorio-inteligente'
    | '/_authenticated/relatorios'
    | '/_authenticated/relatorios-cadastro'
    | '/_authenticated/relatorios-consolidado'
    | '/_authenticated/relatorios-executivo'
    | '/_authenticated/relatorios-gerenciais'
    | '/_authenticated/relatorios-piso'
    | '/_authenticated/relatorios-profissional'
    | '/_authenticated/relatorios-status'
    | '/_authenticated/sala-situacao'
    | '/_authenticated/saude'
    | '/_authenticated/seguranca'
    | '/_authenticated/setores'
    | '/_authenticated/tipos-unidade'
    | '/_authenticated/usuarios'
    | '/validar/$id'
    | '/_authenticated/administracao/mural'
    | '/_authenticated/administracao/sistemas-externos'
    | '/_authenticated/cargos/$id'
    | '/_authenticated/competencias/$id'
    | '/_authenticated/configuracao/perfis'
    | '/_authenticated/frequencia/contratados'
    | '/_authenticated/frequencia/efetivos'
    | '/_authenticated/frequencias_/$id'
    | '/_authenticated/funcoes/$id'
    | '/_authenticated/gestao-pessoas/distribuicao-setor'
    | '/_authenticated/gestao-pessoas/lotacao'
    | '/_authenticated/gestao-pessoas/situacao-funcional'
    | '/_authenticated/meu-perfil/assinatura'
    | '/_authenticated/piso-enfermagem/extracao'
    | '/_authenticated/piso-enfermagem/importar'
    | '/_authenticated/piso-enfermagem/importar-contratados'
    | '/_authenticated/piso-enfermagem/importar-efetivos'
    | '/_authenticated/profissionais/$id'
    | '/_authenticated/relatorios-gerenciais/auditoria'
    | '/_authenticated/relatorios-gerenciais/cargos'
    | '/_authenticated/relatorios-gerenciais/estrutura'
    | '/_authenticated/relatorios-gerenciais/funcoes'
    | '/_authenticated/relatorios-gerenciais/piso'
    | '/_authenticated/relatorios-gerenciais/profissionais'
    | '/_authenticated/relatorios-gerenciais/salarios'
    | '/_authenticated/relatorios-gerenciais/setores'
    | '/_authenticated/relatorios-gerenciais/unidades'
    | '/_authenticated/setores/$id'
    | '/_authenticated/unidades/$id'
    | '/_authenticated/usuarios/$id'
    | '/_authenticated/configuracao/'
    | '/_authenticated/gestao-pessoas/'
    | '/_authenticated/piso-enfermagem/'
    | '/_authenticated/relatorios-gerenciais/'
    | '/_authenticated/unidades/'
    | '/_authenticated/configuracao/perfis/$id'
    | '/api/public/documento-pdf/$id'
    | '/api/public/hooks/deadline-check'
    | '/api/public/hooks/eventos-worker'
    | '/api/public/hooks/purgar-documentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SmtpTestRoute: typeof SmtpTestRoute
  ValidarIdRoute: typeof ValidarIdRoute
  ApiPublicDocumentoPdfIdRoute: typeof ApiPublicDocumentoPdfIdRoute
  ApiPublicHooksDeadlineCheckRoute: typeof ApiPublicHooksDeadlineCheckRoute
  ApiPublicHooksEventosWorkerRoute: typeof ApiPublicHooksEventosWorkerRoute
  ApiPublicHooksPurgarDocumentosRoute: typeof ApiPublicHooksPurgarDocumentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smtp-test': {
      id: '/smtp-test'
      path: '/smtp-test'
      fullPath: '/smtp-test'
      preLoaderRoute: typeof SmtpTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$id': {
      id: '/validar/$id'
      path: '/validar/$id'
      fullPath: '/validar/$id'
      preLoaderRoute: typeof ValidarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tipos-unidade': {
      id: '/_authenticated/tipos-unidade'
      path: '/tipos-unidade'
      fullPath: '/tipos-unidade'
      preLoaderRoute: typeof AuthenticatedTiposUnidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setores': {
      id: '/_authenticated/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof AuthenticatedSetoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saude': {
      id: '/_authenticated/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof AuthenticatedSaudeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sala-situacao': {
      id: '/_authenticated/sala-situacao'
      path: '/sala-situacao'
      fullPath: '/sala-situacao'
      preLoaderRoute: typeof AuthenticatedSalaSituacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-status': {
      id: '/_authenticated/relatorios-status'
      path: '/relatorios-status'
      fullPath: '/relatorios-status'
      preLoaderRoute: typeof AuthenticatedRelatoriosStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-profissional': {
      id: '/_authenticated/relatorios-profissional'
      path: '/relatorios-profissional'
      fullPath: '/relatorios-profissional'
      preLoaderRoute: typeof AuthenticatedRelatoriosProfissionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-piso': {
      id: '/_authenticated/relatorios-piso'
      path: '/relatorios-piso'
      fullPath: '/relatorios-piso'
      preLoaderRoute: typeof AuthenticatedRelatoriosPisoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-gerenciais': {
      id: '/_authenticated/relatorios-gerenciais'
      path: '/relatorios-gerenciais'
      fullPath: '/relatorios-gerenciais'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-executivo': {
      id: '/_authenticated/relatorios-executivo'
      path: '/relatorios-executivo'
      fullPath: '/relatorios-executivo'
      preLoaderRoute: typeof AuthenticatedRelatoriosExecutivoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-consolidado': {
      id: '/_authenticated/relatorios-consolidado'
      path: '/relatorios-consolidado'
      fullPath: '/relatorios-consolidado'
      preLoaderRoute: typeof AuthenticatedRelatoriosConsolidadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-cadastro': {
      id: '/_authenticated/relatorios-cadastro'
      path: '/relatorios-cadastro'
      fullPath: '/relatorios-cadastro'
      preLoaderRoute: typeof AuthenticatedRelatoriosCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorio-inteligente': {
      id: '/_authenticated/relatorio-inteligente'
      path: '/relatorio-inteligente'
      fullPath: '/relatorio-inteligente'
      preLoaderRoute: typeof AuthenticatedRelatorioInteligenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/layouts-importacao': {
      id: '/_authenticated/layouts-importacao'
      path: '/layouts-importacao'
      fullPath: '/layouts-importacao'
      preLoaderRoute: typeof AuthenticatedLayoutsImportacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-rh': {
      id: '/_authenticated/gestao-rh'
      path: '/gestao-rh'
      fullPath: '/gestao-rh'
      preLoaderRoute: typeof AuthenticatedGestaoRhRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-profissionais': {
      id: '/_authenticated/gestao-profissionais'
      path: '/gestao-profissionais'
      fullPath: '/gestao-profissionais'
      preLoaderRoute: typeof AuthenticatedGestaoProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frequencias': {
      id: '/_authenticated/frequencias'
      path: '/frequencias'
      fullPath: '/frequencias'
      preLoaderRoute: typeof AuthenticatedFrequenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feriados': {
      id: '/_authenticated/feriados'
      path: '/feriados'
      fullPath: '/feriados'
      preLoaderRoute: typeof AuthenticatedFeriadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos-emitidos': {
      id: '/_authenticated/documentos-emitidos'
      path: '/documentos-emitidos'
      fullPath: '/documentos-emitidos'
      preLoaderRoute: typeof AuthenticatedDocumentosEmitidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/controle-forca-trabalho': {
      id: '/_authenticated/controle-forca-trabalho'
      path: '/controle-forca-trabalho'
      fullPath: '/controle-forca-trabalho'
      preLoaderRoute: typeof AuthenticatedControleForcaTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/competencias': {
      id: '/_authenticated/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof AuthenticatedCompetenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cargos-funcoes': {
      id: '/_authenticated/cargos-funcoes'
      path: '/cargos-funcoes'
      fullPath: '/cargos-funcoes'
      preLoaderRoute: typeof AuthenticatedCargosFuncoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinar-pdf': {
      id: '/_authenticated/assinar-pdf'
      path: '/assinar-pdf'
      fullPath: '/assinar-pdf'
      preLoaderRoute: typeof AuthenticatedAssinarPdfRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analitico': {
      id: '/_authenticated/analitico'
      path: '/analitico'
      fullPath: '/analitico'
      preLoaderRoute: typeof AuthenticatedAnaliticoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unidades/': {
      id: '/_authenticated/unidades/'
      path: '/unidades'
      fullPath: '/unidades/'
      preLoaderRoute: typeof AuthenticatedUnidadesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios-gerenciais/': {
      id: '/_authenticated/relatorios-gerenciais/'
      path: '/'
      fullPath: '/relatorios-gerenciais/'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisIndexRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/piso-enfermagem/': {
      id: '/_authenticated/piso-enfermagem/'
      path: '/piso-enfermagem'
      fullPath: '/piso-enfermagem/'
      preLoaderRoute: typeof AuthenticatedPisoEnfermagemIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-pessoas/': {
      id: '/_authenticated/gestao-pessoas/'
      path: '/gestao-pessoas'
      fullPath: '/gestao-pessoas/'
      preLoaderRoute: typeof AuthenticatedGestaoPessoasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracao/': {
      id: '/_authenticated/configuracao/'
      path: '/configuracao'
      fullPath: '/configuracao/'
      preLoaderRoute: typeof AuthenticatedConfiguracaoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usuarios/$id': {
      id: '/_authenticated/usuarios/$id'
      path: '/$id'
      fullPath: '/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedUsuariosRoute
    }
    '/_authenticated/unidades/$id': {
      id: '/_authenticated/unidades/$id'
      path: '/unidades/$id'
      fullPath: '/unidades/$id'
      preLoaderRoute: typeof AuthenticatedUnidadesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setores/$id': {
      id: '/_authenticated/setores/$id'
      path: '/$id'
      fullPath: '/setores/$id'
      preLoaderRoute: typeof AuthenticatedSetoresIdRouteImport
      parentRoute: typeof AuthenticatedSetoresRoute
    }
    '/_authenticated/relatorios-gerenciais/unidades': {
      id: '/_authenticated/relatorios-gerenciais/unidades'
      path: '/unidades'
      fullPath: '/relatorios-gerenciais/unidades'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisUnidadesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/setores': {
      id: '/_authenticated/relatorios-gerenciais/setores'
      path: '/setores'
      fullPath: '/relatorios-gerenciais/setores'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisSetoresRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/salarios': {
      id: '/_authenticated/relatorios-gerenciais/salarios'
      path: '/salarios'
      fullPath: '/relatorios-gerenciais/salarios'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisSalariosRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/profissionais': {
      id: '/_authenticated/relatorios-gerenciais/profissionais'
      path: '/profissionais'
      fullPath: '/relatorios-gerenciais/profissionais'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/piso': {
      id: '/_authenticated/relatorios-gerenciais/piso'
      path: '/piso'
      fullPath: '/relatorios-gerenciais/piso'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisPisoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/funcoes': {
      id: '/_authenticated/relatorios-gerenciais/funcoes'
      path: '/funcoes'
      fullPath: '/relatorios-gerenciais/funcoes'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisFuncoesRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/estrutura': {
      id: '/_authenticated/relatorios-gerenciais/estrutura'
      path: '/estrutura'
      fullPath: '/relatorios-gerenciais/estrutura'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisEstruturaRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/cargos': {
      id: '/_authenticated/relatorios-gerenciais/cargos'
      path: '/cargos'
      fullPath: '/relatorios-gerenciais/cargos'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisCargosRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/relatorios-gerenciais/auditoria': {
      id: '/_authenticated/relatorios-gerenciais/auditoria'
      path: '/auditoria'
      fullPath: '/relatorios-gerenciais/auditoria'
      preLoaderRoute: typeof AuthenticatedRelatoriosGerenciaisAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRelatoriosGerenciaisRoute
    }
    '/_authenticated/profissionais/$id': {
      id: '/_authenticated/profissionais/$id'
      path: '/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof AuthenticatedProfissionaisIdRouteImport
      parentRoute: typeof AuthenticatedProfissionaisRoute
    }
    '/_authenticated/piso-enfermagem/importar-efetivos': {
      id: '/_authenticated/piso-enfermagem/importar-efetivos'
      path: '/piso-enfermagem/importar-efetivos'
      fullPath: '/piso-enfermagem/importar-efetivos'
      preLoaderRoute: typeof AuthenticatedPisoEnfermagemImportarEfetivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/piso-enfermagem/importar-contratados': {
      id: '/_authenticated/piso-enfermagem/importar-contratados'
      path: '/piso-enfermagem/importar-contratados'
      fullPath: '/piso-enfermagem/importar-contratados'
      preLoaderRoute: typeof AuthenticatedPisoEnfermagemImportarContratadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/piso-enfermagem/importar': {
      id: '/_authenticated/piso-enfermagem/importar'
      path: '/piso-enfermagem/importar'
      fullPath: '/piso-enfermagem/importar'
      preLoaderRoute: typeof AuthenticatedPisoEnfermagemImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/piso-enfermagem/extracao': {
      id: '/_authenticated/piso-enfermagem/extracao'
      path: '/piso-enfermagem/extracao'
      fullPath: '/piso-enfermagem/extracao'
      preLoaderRoute: typeof AuthenticatedPisoEnfermagemExtracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil/assinatura': {
      id: '/_authenticated/meu-perfil/assinatura'
      path: '/meu-perfil/assinatura'
      fullPath: '/meu-perfil/assinatura'
      preLoaderRoute: typeof AuthenticatedMeuPerfilAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-pessoas/situacao-funcional': {
      id: '/_authenticated/gestao-pessoas/situacao-funcional'
      path: '/gestao-pessoas/situacao-funcional'
      fullPath: '/gestao-pessoas/situacao-funcional'
      preLoaderRoute: typeof AuthenticatedGestaoPessoasSituacaoFuncionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-pessoas/lotacao': {
      id: '/_authenticated/gestao-pessoas/lotacao'
      path: '/gestao-pessoas/lotacao'
      fullPath: '/gestao-pessoas/lotacao'
      preLoaderRoute: typeof AuthenticatedGestaoPessoasLotacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gestao-pessoas/distribuicao-setor': {
      id: '/_authenticated/gestao-pessoas/distribuicao-setor'
      path: '/gestao-pessoas/distribuicao-setor'
      fullPath: '/gestao-pessoas/distribuicao-setor'
      preLoaderRoute: typeof AuthenticatedGestaoPessoasDistribuicaoSetorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funcoes/$id': {
      id: '/_authenticated/funcoes/$id'
      path: '/funcoes/$id'
      fullPath: '/funcoes/$id'
      preLoaderRoute: typeof AuthenticatedFuncoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frequencias_/$id': {
      id: '/_authenticated/frequencias_/$id'
      path: '/frequencias/$id'
      fullPath: '/frequencias/$id'
      preLoaderRoute: typeof AuthenticatedFrequenciasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frequencia/efetivos': {
      id: '/_authenticated/frequencia/efetivos'
      path: '/frequencia/efetivos'
      fullPath: '/frequencia/efetivos'
      preLoaderRoute: typeof AuthenticatedFrequenciaEfetivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/frequencia/contratados': {
      id: '/_authenticated/frequencia/contratados'
      path: '/frequencia/contratados'
      fullPath: '/frequencia/contratados'
      preLoaderRoute: typeof AuthenticatedFrequenciaContratadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracao/perfis': {
      id: '/_authenticated/configuracao/perfis'
      path: '/configuracao/perfis'
      fullPath: '/configuracao/perfis'
      preLoaderRoute: typeof AuthenticatedConfiguracaoPerfisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/competencias/$id': {
      id: '/_authenticated/competencias/$id'
      path: '/$id'
      fullPath: '/competencias/$id'
      preLoaderRoute: typeof AuthenticatedCompetenciasIdRouteImport
      parentRoute: typeof AuthenticatedCompetenciasRoute
    }
    '/_authenticated/cargos/$id': {
      id: '/_authenticated/cargos/$id'
      path: '/cargos/$id'
      fullPath: '/cargos/$id'
      preLoaderRoute: typeof AuthenticatedCargosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/sistemas-externos': {
      id: '/_authenticated/administracao/sistemas-externos'
      path: '/administracao/sistemas-externos'
      fullPath: '/administracao/sistemas-externos'
      preLoaderRoute: typeof AuthenticatedAdministracaoSistemasExternosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao/mural': {
      id: '/_authenticated/administracao/mural'
      path: '/administracao/mural'
      fullPath: '/administracao/mural'
      preLoaderRoute: typeof AuthenticatedAdministracaoMuralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/purgar-documentos': {
      id: '/api/public/hooks/purgar-documentos'
      path: '/api/public/hooks/purgar-documentos'
      fullPath: '/api/public/hooks/purgar-documentos'
      preLoaderRoute: typeof ApiPublicHooksPurgarDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eventos-worker': {
      id: '/api/public/hooks/eventos-worker'
      path: '/api/public/hooks/eventos-worker'
      fullPath: '/api/public/hooks/eventos-worker'
      preLoaderRoute: typeof ApiPublicHooksEventosWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deadline-check': {
      id: '/api/public/hooks/deadline-check'
      path: '/api/public/hooks/deadline-check'
      fullPath: '/api/public/hooks/deadline-check'
      preLoaderRoute: typeof ApiPublicHooksDeadlineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/documento-pdf/$id': {
      id: '/api/public/documento-pdf/$id'
      path: '/api/public/documento-pdf/$id'
      fullPath: '/api/public/documento-pdf/$id'
      preLoaderRoute: typeof ApiPublicDocumentoPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracao/perfis/$id': {
      id: '/_authenticated/configuracao/perfis/$id'
      path: '/$id'
      fullPath: '/configuracao/perfis/$id'
      preLoaderRoute: typeof AuthenticatedConfiguracaoPerfisIdRouteImport
      parentRoute: typeof AuthenticatedConfiguracaoPerfisRoute
    }
  }
}

interface AuthenticatedCompetenciasRouteChildren {
  AuthenticatedCompetenciasIdRoute: typeof AuthenticatedCompetenciasIdRoute
}

const AuthenticatedCompetenciasRouteChildren: AuthenticatedCompetenciasRouteChildren =
  {
    AuthenticatedCompetenciasIdRoute: AuthenticatedCompetenciasIdRoute,
  }

const AuthenticatedCompetenciasRouteWithChildren =
  AuthenticatedCompetenciasRoute._addFileChildren(
    AuthenticatedCompetenciasRouteChildren,
  )

interface AuthenticatedProfissionaisRouteChildren {
  AuthenticatedProfissionaisIdRoute: typeof AuthenticatedProfissionaisIdRoute
}

const AuthenticatedProfissionaisRouteChildren: AuthenticatedProfissionaisRouteChildren =
  {
    AuthenticatedProfissionaisIdRoute: AuthenticatedProfissionaisIdRoute,
  }

const AuthenticatedProfissionaisRouteWithChildren =
  AuthenticatedProfissionaisRoute._addFileChildren(
    AuthenticatedProfissionaisRouteChildren,
  )

interface AuthenticatedRelatoriosGerenciaisRouteChildren {
  AuthenticatedRelatoriosGerenciaisAuditoriaRoute: typeof AuthenticatedRelatoriosGerenciaisAuditoriaRoute
  AuthenticatedRelatoriosGerenciaisCargosRoute: typeof AuthenticatedRelatoriosGerenciaisCargosRoute
  AuthenticatedRelatoriosGerenciaisEstruturaRoute: typeof AuthenticatedRelatoriosGerenciaisEstruturaRoute
  AuthenticatedRelatoriosGerenciaisFuncoesRoute: typeof AuthenticatedRelatoriosGerenciaisFuncoesRoute
  AuthenticatedRelatoriosGerenciaisPisoRoute: typeof AuthenticatedRelatoriosGerenciaisPisoRoute
  AuthenticatedRelatoriosGerenciaisProfissionaisRoute: typeof AuthenticatedRelatoriosGerenciaisProfissionaisRoute
  AuthenticatedRelatoriosGerenciaisSalariosRoute: typeof AuthenticatedRelatoriosGerenciaisSalariosRoute
  AuthenticatedRelatoriosGerenciaisSetoresRoute: typeof AuthenticatedRelatoriosGerenciaisSetoresRoute
  AuthenticatedRelatoriosGerenciaisUnidadesRoute: typeof AuthenticatedRelatoriosGerenciaisUnidadesRoute
  AuthenticatedRelatoriosGerenciaisIndexRoute: typeof AuthenticatedRelatoriosGerenciaisIndexRoute
}

const AuthenticatedRelatoriosGerenciaisRouteChildren: AuthenticatedRelatoriosGerenciaisRouteChildren =
  {
    AuthenticatedRelatoriosGerenciaisAuditoriaRoute:
      AuthenticatedRelatoriosGerenciaisAuditoriaRoute,
    AuthenticatedRelatoriosGerenciaisCargosRoute:
      AuthenticatedRelatoriosGerenciaisCargosRoute,
    AuthenticatedRelatoriosGerenciaisEstruturaRoute:
      AuthenticatedRelatoriosGerenciaisEstruturaRoute,
    AuthenticatedRelatoriosGerenciaisFuncoesRoute:
      AuthenticatedRelatoriosGerenciaisFuncoesRoute,
    AuthenticatedRelatoriosGerenciaisPisoRoute:
      AuthenticatedRelatoriosGerenciaisPisoRoute,
    AuthenticatedRelatoriosGerenciaisProfissionaisRoute:
      AuthenticatedRelatoriosGerenciaisProfissionaisRoute,
    AuthenticatedRelatoriosGerenciaisSalariosRoute:
      AuthenticatedRelatoriosGerenciaisSalariosRoute,
    AuthenticatedRelatoriosGerenciaisSetoresRoute:
      AuthenticatedRelatoriosGerenciaisSetoresRoute,
    AuthenticatedRelatoriosGerenciaisUnidadesRoute:
      AuthenticatedRelatoriosGerenciaisUnidadesRoute,
    AuthenticatedRelatoriosGerenciaisIndexRoute:
      AuthenticatedRelatoriosGerenciaisIndexRoute,
  }

const AuthenticatedRelatoriosGerenciaisRouteWithChildren =
  AuthenticatedRelatoriosGerenciaisRoute._addFileChildren(
    AuthenticatedRelatoriosGerenciaisRouteChildren,
  )

interface AuthenticatedSetoresRouteChildren {
  AuthenticatedSetoresIdRoute: typeof AuthenticatedSetoresIdRoute
}

const AuthenticatedSetoresRouteChildren: AuthenticatedSetoresRouteChildren = {
  AuthenticatedSetoresIdRoute: AuthenticatedSetoresIdRoute,
}

const AuthenticatedSetoresRouteWithChildren =
  AuthenticatedSetoresRoute._addFileChildren(AuthenticatedSetoresRouteChildren)

interface AuthenticatedUsuariosRouteChildren {
  AuthenticatedUsuariosIdRoute: typeof AuthenticatedUsuariosIdRoute
}

const AuthenticatedUsuariosRouteChildren: AuthenticatedUsuariosRouteChildren = {
  AuthenticatedUsuariosIdRoute: AuthenticatedUsuariosIdRoute,
}

const AuthenticatedUsuariosRouteWithChildren =
  AuthenticatedUsuariosRoute._addFileChildren(
    AuthenticatedUsuariosRouteChildren,
  )

interface AuthenticatedConfiguracaoPerfisRouteChildren {
  AuthenticatedConfiguracaoPerfisIdRoute: typeof AuthenticatedConfiguracaoPerfisIdRoute
}

const AuthenticatedConfiguracaoPerfisRouteChildren: AuthenticatedConfiguracaoPerfisRouteChildren =
  {
    AuthenticatedConfiguracaoPerfisIdRoute:
      AuthenticatedConfiguracaoPerfisIdRoute,
  }

const AuthenticatedConfiguracaoPerfisRouteWithChildren =
  AuthenticatedConfiguracaoPerfisRoute._addFileChildren(
    AuthenticatedConfiguracaoPerfisRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnaliticoRoute: typeof AuthenticatedAnaliticoRoute
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedAssinarPdfRoute: typeof AuthenticatedAssinarPdfRoute
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCargosFuncoesRoute: typeof AuthenticatedCargosFuncoesRoute
  AuthenticatedCompetenciasRoute: typeof AuthenticatedCompetenciasRouteWithChildren
  AuthenticatedControleForcaTrabalhoRoute: typeof AuthenticatedControleForcaTrabalhoRoute
  AuthenticatedDocumentosEmitidosRoute: typeof AuthenticatedDocumentosEmitidosRoute
  AuthenticatedFeriadosRoute: typeof AuthenticatedFeriadosRoute
  AuthenticatedFrequenciasRoute: typeof AuthenticatedFrequenciasRoute
  AuthenticatedGestaoProfissionaisRoute: typeof AuthenticatedGestaoProfissionaisRoute
  AuthenticatedGestaoRhRoute: typeof AuthenticatedGestaoRhRoute
  AuthenticatedLayoutsImportacaoRoute: typeof AuthenticatedLayoutsImportacaoRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRouteWithChildren
  AuthenticatedRelatorioInteligenteRoute: typeof AuthenticatedRelatorioInteligenteRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRelatoriosCadastroRoute: typeof AuthenticatedRelatoriosCadastroRoute
  AuthenticatedRelatoriosConsolidadoRoute: typeof AuthenticatedRelatoriosConsolidadoRoute
  AuthenticatedRelatoriosExecutivoRoute: typeof AuthenticatedRelatoriosExecutivoRoute
  AuthenticatedRelatoriosGerenciaisRoute: typeof AuthenticatedRelatoriosGerenciaisRouteWithChildren
  AuthenticatedRelatoriosPisoRoute: typeof AuthenticatedRelatoriosPisoRoute
  AuthenticatedRelatoriosProfissionalRoute: typeof AuthenticatedRelatoriosProfissionalRoute
  AuthenticatedRelatoriosStatusRoute: typeof AuthenticatedRelatoriosStatusRoute
  AuthenticatedSalaSituacaoRoute: typeof AuthenticatedSalaSituacaoRoute
  AuthenticatedSaudeRoute: typeof AuthenticatedSaudeRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedSetoresRoute: typeof AuthenticatedSetoresRouteWithChildren
  AuthenticatedTiposUnidadeRoute: typeof AuthenticatedTiposUnidadeRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRouteWithChildren
  AuthenticatedAdministracaoMuralRoute: typeof AuthenticatedAdministracaoMuralRoute
  AuthenticatedAdministracaoSistemasExternosRoute: typeof AuthenticatedAdministracaoSistemasExternosRoute
  AuthenticatedCargosIdRoute: typeof AuthenticatedCargosIdRoute
  AuthenticatedConfiguracaoPerfisRoute: typeof AuthenticatedConfiguracaoPerfisRouteWithChildren
  AuthenticatedFrequenciaContratadosRoute: typeof AuthenticatedFrequenciaContratadosRoute
  AuthenticatedFrequenciaEfetivosRoute: typeof AuthenticatedFrequenciaEfetivosRoute
  AuthenticatedFrequenciasIdRoute: typeof AuthenticatedFrequenciasIdRoute
  AuthenticatedFuncoesIdRoute: typeof AuthenticatedFuncoesIdRoute
  AuthenticatedGestaoPessoasDistribuicaoSetorRoute: typeof AuthenticatedGestaoPessoasDistribuicaoSetorRoute
  AuthenticatedGestaoPessoasLotacaoRoute: typeof AuthenticatedGestaoPessoasLotacaoRoute
  AuthenticatedGestaoPessoasSituacaoFuncionalRoute: typeof AuthenticatedGestaoPessoasSituacaoFuncionalRoute
  AuthenticatedMeuPerfilAssinaturaRoute: typeof AuthenticatedMeuPerfilAssinaturaRoute
  AuthenticatedPisoEnfermagemExtracaoRoute: typeof AuthenticatedPisoEnfermagemExtracaoRoute
  AuthenticatedPisoEnfermagemImportarRoute: typeof AuthenticatedPisoEnfermagemImportarRoute
  AuthenticatedPisoEnfermagemImportarContratadosRoute: typeof AuthenticatedPisoEnfermagemImportarContratadosRoute
  AuthenticatedPisoEnfermagemImportarEfetivosRoute: typeof AuthenticatedPisoEnfermagemImportarEfetivosRoute
  AuthenticatedUnidadesIdRoute: typeof AuthenticatedUnidadesIdRoute
  AuthenticatedConfiguracaoIndexRoute: typeof AuthenticatedConfiguracaoIndexRoute
  AuthenticatedGestaoPessoasIndexRoute: typeof AuthenticatedGestaoPessoasIndexRoute
  AuthenticatedPisoEnfermagemIndexRoute: typeof AuthenticatedPisoEnfermagemIndexRoute
  AuthenticatedUnidadesIndexRoute: typeof AuthenticatedUnidadesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnaliticoRoute: AuthenticatedAnaliticoRoute,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedAssinarPdfRoute: AuthenticatedAssinarPdfRoute,
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCargosFuncoesRoute: AuthenticatedCargosFuncoesRoute,
  AuthenticatedCompetenciasRoute: AuthenticatedCompetenciasRouteWithChildren,
  AuthenticatedControleForcaTrabalhoRoute:
    AuthenticatedControleForcaTrabalhoRoute,
  AuthenticatedDocumentosEmitidosRoute: AuthenticatedDocumentosEmitidosRoute,
  AuthenticatedFeriadosRoute: AuthenticatedFeriadosRoute,
  AuthenticatedFrequenciasRoute: AuthenticatedFrequenciasRoute,
  AuthenticatedGestaoProfissionaisRoute: AuthenticatedGestaoProfissionaisRoute,
  AuthenticatedGestaoRhRoute: AuthenticatedGestaoRhRoute,
  AuthenticatedLayoutsImportacaoRoute: AuthenticatedLayoutsImportacaoRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRouteWithChildren,
  AuthenticatedRelatorioInteligenteRoute:
    AuthenticatedRelatorioInteligenteRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRelatoriosCadastroRoute: AuthenticatedRelatoriosCadastroRoute,
  AuthenticatedRelatoriosConsolidadoRoute:
    AuthenticatedRelatoriosConsolidadoRoute,
  AuthenticatedRelatoriosExecutivoRoute: AuthenticatedRelatoriosExecutivoRoute,
  AuthenticatedRelatoriosGerenciaisRoute:
    AuthenticatedRelatoriosGerenciaisRouteWithChildren,
  AuthenticatedRelatoriosPisoRoute: AuthenticatedRelatoriosPisoRoute,
  AuthenticatedRelatoriosProfissionalRoute:
    AuthenticatedRelatoriosProfissionalRoute,
  AuthenticatedRelatoriosStatusRoute: AuthenticatedRelatoriosStatusRoute,
  AuthenticatedSalaSituacaoRoute: AuthenticatedSalaSituacaoRoute,
  AuthenticatedSaudeRoute: AuthenticatedSaudeRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedSetoresRoute: AuthenticatedSetoresRouteWithChildren,
  AuthenticatedTiposUnidadeRoute: AuthenticatedTiposUnidadeRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRouteWithChildren,
  AuthenticatedAdministracaoMuralRoute: AuthenticatedAdministracaoMuralRoute,
  AuthenticatedAdministracaoSistemasExternosRoute:
    AuthenticatedAdministracaoSistemasExternosRoute,
  AuthenticatedCargosIdRoute: AuthenticatedCargosIdRoute,
  AuthenticatedConfiguracaoPerfisRoute:
    AuthenticatedConfiguracaoPerfisRouteWithChildren,
  AuthenticatedFrequenciaContratadosRoute:
    AuthenticatedFrequenciaContratadosRoute,
  AuthenticatedFrequenciaEfetivosRoute: AuthenticatedFrequenciaEfetivosRoute,
  AuthenticatedFrequenciasIdRoute: AuthenticatedFrequenciasIdRoute,
  AuthenticatedFuncoesIdRoute: AuthenticatedFuncoesIdRoute,
  AuthenticatedGestaoPessoasDistribuicaoSetorRoute:
    AuthenticatedGestaoPessoasDistribuicaoSetorRoute,
  AuthenticatedGestaoPessoasLotacaoRoute:
    AuthenticatedGestaoPessoasLotacaoRoute,
  AuthenticatedGestaoPessoasSituacaoFuncionalRoute:
    AuthenticatedGestaoPessoasSituacaoFuncionalRoute,
  AuthenticatedMeuPerfilAssinaturaRoute: AuthenticatedMeuPerfilAssinaturaRoute,
  AuthenticatedPisoEnfermagemExtracaoRoute:
    AuthenticatedPisoEnfermagemExtracaoRoute,
  AuthenticatedPisoEnfermagemImportarRoute:
    AuthenticatedPisoEnfermagemImportarRoute,
  AuthenticatedPisoEnfermagemImportarContratadosRoute:
    AuthenticatedPisoEnfermagemImportarContratadosRoute,
  AuthenticatedPisoEnfermagemImportarEfetivosRoute:
    AuthenticatedPisoEnfermagemImportarEfetivosRoute,
  AuthenticatedUnidadesIdRoute: AuthenticatedUnidadesIdRoute,
  AuthenticatedConfiguracaoIndexRoute: AuthenticatedConfiguracaoIndexRoute,
  AuthenticatedGestaoPessoasIndexRoute: AuthenticatedGestaoPessoasIndexRoute,
  AuthenticatedPisoEnfermagemIndexRoute: AuthenticatedPisoEnfermagemIndexRoute,
  AuthenticatedUnidadesIndexRoute: AuthenticatedUnidadesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SmtpTestRoute: SmtpTestRoute,
  ValidarIdRoute: ValidarIdRoute,
  ApiPublicDocumentoPdfIdRoute: ApiPublicDocumentoPdfIdRoute,
  ApiPublicHooksDeadlineCheckRoute: ApiPublicHooksDeadlineCheckRoute,
  ApiPublicHooksEventosWorkerRoute: ApiPublicHooksEventosWorkerRoute,
  ApiPublicHooksPurgarDocumentosRoute: ApiPublicHooksPurgarDocumentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
